version: "3.1"
services:
  portal:
    image: nginx:stable-perl
    container_name: portal
    ports:
      - "${PORTAL_PORT}:80"
    volumes:
      - ./microservices/portal/web:/usr/share/nginx/html:ro
    links:
      - sms_group
    env_file: ./.env

  sms_group:
    image: node:12.18.4
    container_name: sms_group
    working_dir: /application
    volumes:
      - ./microservices/sms_group_services:/application
    links:
      - mysql
    ports:
      - "${API_PORT}:3000"
    command: ['npm', 'start']
    env_file: ./.env
    environment:
      "NODE_ENV": "${NODE_ENV}"

  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: sms_group_mysql
    volumes:
      - ./servers/mysql/data:/var/lib/mysql
    restart: always
    ports:
      - "3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"